// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QNNrDSpYAPBxdtZuc1nFIBjILrjIG6o',
    appId: '1:743093099881:android:4ba53c61014727afea31f8',
    messagingSenderId: '743093099881',
    projectId: 'umgc-aio',
    databaseURL: 'https://umgc-aio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umgc-aio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohrmPxAWDM6BAODsnv8zah4mK_YX8BC8',
    appId: '1:743093099881:ios:c587677a137282dbea31f8',
    messagingSenderId: '743093099881',
    projectId: 'umgc-aio',
    databaseURL: 'https://umgc-aio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umgc-aio.appspot.com',
    iosClientId: '743093099881-hd1f6qe9q3u9qtkik423teavtsl9pkk6.apps.googleusercontent.com',
    iosBundleId: 'com.umgcambodia.nenamProd',
  );
}
